### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ASNNetworks** [Mohlsson/ReplayLightsHistory#25]
Does this module still even work? I installed and have set up everything, but none of my lights seem to turn on, while they were on during the same times for the last 7 days. Installed through HACS, this is my config:

```
replay_lights:
  hassDir: '/config'
  databaseType: sqlite3
  databaseHost: "localhost"
  databaseSchema: "homeassistant"
  module: replay_lights
  class: ReplayLights
  numberOfDaysBack: 7
  deviceType: "light"
  enableTag: "input_boolean.scene_vakantie"
  enableVal: "on"
  excludeList: "light.woonkamer_z_lampen,light.z_lampen_kamers,light.wc_z_lampen,light.gang_boven_z_lampen,light.woonkamer_z_disco"  
```
